# This is a basic workflow to help you get started with Actions

name: Latest DEV Blog post workflow

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 1/2 * * *'
  workflow_dispatch:
  

jobs:
   update-readme-with-blog:
    name: Update README with latest blog post
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: gautamkrishnar/blog-postworkflow@master
        with:
          comment-tag-name: "BLOG-POST-LIST"
          feed_list: https://dev.to/feed/ansh47
